openapi: 3.0.1

info:
  title: YuChat Bot API
  version: 2.0.0
  description: Публичный API для работы с YuChat.
  contact:
    name: Команда YuChat
    url: https://www.yuchat.ai
    email: support@yuchat.ai

servers:
  - url: https://yuchat.ai/public/v2

tags:
  - name: message
    description: отправка/редактирование/удаление сообщений
  - name: chat
    description: создание чатов, просмотр/приглашение участников в чат
  - name: member
    description: посмотр участников воркспейса
  - name: updates
    description: получение всех событий, адресованных боту
  - name: file
    description: получение ссылки для загрузки файлов

paths:
  /ping:
    get:
      description: Пинг до API
      tags:
        - ping
      operationId: ping
      responses:
        "200":
          description: Сообщение с серверным временем
          content:
            application/json:
              schema:
                type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Токен, который можно получить от aibot@yuchat.ai с помощью команды /botcreate.
security:
  - bearerAuth: [ ]

